## In this demo, I will show the averaging in different dimentional order will result different averaging values when the dataset contains nan values.

In [2]:
import numpy as np
import xarray as xr

In [3]:
np.random.seed(0)
X = np.random.rand(3,3,3)
X[1,2,1] = np.nan
X[0,1,1] = np.nan
X[2,1,2] = np.nan
X = xr.DataArray(X, dims=('x','y','z'))
X

<xarray.DataArray (x: 3, y: 3, z: 3)>
array([[[0.5488135 , 0.71518937, 0.60276338],
        [0.54488318,        nan, 0.64589411],
        [0.43758721, 0.891773  , 0.96366276]],

       [[0.38344152, 0.79172504, 0.52889492],
        [0.56804456, 0.92559664, 0.07103606],
        [0.0871293 ,        nan, 0.83261985]],

       [[0.77815675, 0.87001215, 0.97861834],
        [0.79915856, 0.46147936,        nan],
        [0.11827443, 0.63992102, 0.14335329]]])
Dimensions without coordinates: x, y, z

In [4]:
x1 = X.mean(axis=0)
x3 = x1.mean(axis=0)
x3

<xarray.DataArray (z: 3)>
array([0.47394322, 0.75056462, 0.56947864])
Dimensions without coordinates: z

In [5]:
x2 = X.mean(axis=1)
x4 = x2.mean(axis=0)
x4

<xarray.DataArray (z: 3)>
array([0.47394322, 0.77309318, 0.59198095])
Dimensions without coordinates: z

In [6]:
x5 = X.values
x5 = x5.reshape(9,3)
x5

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318,        nan, 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 ,        nan, 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936,        nan],
       [0.11827443, 0.63992102, 0.14335329]])

In [7]:
x6 = np.nanmean(x5, axis=0)
x6

array([0.47394322, 0.75652808, 0.59585534])